yblog/blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('index/', views.index, name='index'),

    # Django 2.0 版本新特性  路由参数的变化（以前是(?P<article_id>[0-9]{4})）
    path('article/<int:article_id>', views.article_page, name='article_page'),
    path('edit/<int:article_id>', views.edit_page, name='edit_page'),
    path('edit_action', views.edit_action, name='edit_action'),
    path('delete/<int:article_id>', views.delete_article, name='delete_article'),
]

yblog/yblog/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    # Django 2.0 include() 中 namespace 的写法不同于之前的版本
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
]

yblog/blog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(null=True)

    def __str__(self):
        return self.title

yblog/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse

from . import models


def index(request):
    articles = models.Article.objects.all()    # 查询所有文章
    return render(request, 'blog/index.html', {'articles': articles})


# 根据文章id 查询文章内容
def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})


# 博客撰写页面
def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})


# 博客撰写以及修改
def edit_action(request):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    article_id = request.POST.get('article_id', '0')
    if article_id == '0':
        models.Article.objects.create(title=title, content=content)   # 写入数据库
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articles': articles})

    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()    # 更新数据库
    return render(request, 'blog/article_page.html', {'article': article})


# 删除博客
def delete_article(request, article_id):
    article_id = request.POST.get(article_id, '0')
    models.Article.objects.filter(pk=str(article_id)).delete()

    return index(request)

yblog/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
</head>
<body>
    <h1>{{ article.title }}</h1>
    <br/>
    <h3>{{ article.content }}</h3>
    <br/><br/>
    <a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
    <br />
    <a href="{% url 'blog:index' %}">返回文章列表</a>
    <br /><br />
    <a href="{% url 'blog:delete_article' article.id %}" style="color: red">删除本篇文章</a>
</body>
</html>

yblog/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
    <h3>在此撰写博客</h3>
    <form action="{% url 'blog:edit_action' %}" method="post">

        {% csrf_token %}  {#防范跨站请求伪造#}

        {% if article %}
            <input type="hidden" name="article_id" value="{{ article.id }}"/>
            <label>文章标题
                <input type="text" name="title" value="{{ article.title }}" />
            </label>
            <br />
            <label>文章内容
                <input type="text" name="content" value="{{ article.content }}" />
            </label>
            <br />
        {% else %}
            <input type="hidden" name="article_id" value="0"/>
            <label>文章标题
                <input type="text" name="title" value="{{ article.title }}" />
            </label>
            <br />
            <label>文章内容
                <input type="text" name="content" value="{{ article.content }}" />
            </label>
            <br />
        {% endif %}
        <input type="submit" />
        <br />
    </form>
</body>
</html>

yblog/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>
        <a href="{% url 'blog:edit_page' 0 %}">新文章</a>
    </h1>

    {% for article in articles %}
        <a href="{% url 'blog:article_page' article.id %}">{{article.title}}</a>
        <br/>
    {#    <h3>{{article.content}}</h3>#}
    {% endfor %}
</body>
</html>